site_name: Calvin
nav:
  - Main:
    - About: el/about.md
    - Link Tree: el/index.md
    - MkDocs: el/mkdocs.md
theme:
  name: material
plugins:
  - redirects:
      redirect_maps:
        'index.md': 'el/index.md'